In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/big_mart_sales.csv")

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [5]:
data.shape

(8523, 12)

In [6]:
data.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [7]:
data.describe

<bound method NDFrame.describe of      Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047
1              DRC01        5.920          Regular         0.019278
2              FDN15       17.500          Low Fat         0.016760
3              FDX07       19.200          Regular         0.000000
4              NCD19        8.930          Low Fat         0.000000
...              ...          ...              ...              ...
8518           FDF22        6.865          Low Fat         0.056783
8519           FDS36        8.380          Regular         0.046982
8520           NCJ29       10.600          Low Fat         0.035186
8521           FDN46        7.210          Regular         0.145221
8522           DRG01       14.800          Low Fat         0.044878

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049
1               Soft Drinks   48.2692            OUT018
2                      Meat  141.6180            OUT049
3     Fruits and Vegetables  182.0950            OUT010
4                 Household   53.8614            OUT013
...                     ...       ...               ...
8518            Snack Foods  214.5218            OUT013
8519           Baking Goods  108.1570            OUT045
8520     Health and Hygiene   85.1224            OUT035
8521            Snack Foods  103.1332            OUT018
8522            Soft Drinks   75.4670            OUT046

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1
1                          2009      Medium               Tier 3
2                          1999      Medium               Tier 1
3                          1998         NaN               Tier 3
4                          1987        High               Tier 3
...                         ...         ...                  ...
8518                       1987        High               Tier 3
8519                       2002         NaN               Tier 2
8520                       2004       Small               Tier 2
8521                       2009      Medium               Tier 3
8522                       1997       Small               Tier 1

            Outlet_Type  Item_Outlet_Sales
0     Supermarket Type1          3735.1380
1     Supermarket Type2           443.4228
2     Supermarket Type1          2097.2700
3         Grocery Store           732.3800
4     Supermarket Type1           994.7052
...                 ...                ...
8518  Supermarket Type1          2778.3834
8519  Supermarket Type1           549.2850
8520  Supermarket Type1          1193.1136
8521  Supermarket Type2          1845.5976
8522  Supermarket Type1           765.6700

[8523 rows x 12 columns]>

Challenge 1: Reading data except for the first few comments or lines written in the file which are not a part of the DataFrame

In [10]:
data_with_rows = pd.read_csv("datasets/big_mart_sales_top_row_error.csv")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

In [13]:
data_with_rows = pd.read_csv("datasets/big_mart_sales_top_row_error.csv", skiprows=5)
data_with_rows.head(3)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700

Challenge 2: Read the files present in multiple directions, using multi directory

In [14]:
import glob

Glob is a library which helps us to read multiple files together

In [15]:
for directory in glob.glob("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/*"):
    print(directory)

/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1987
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/2007
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/2009
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1985
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1997
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1999
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1998
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/2002
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/2004

In [16]:
for directory in glob.glob("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/*"):
    for files in glob.glob(directory + "/*"):
        print(files)

/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1987/1987.csv
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/2007/2007.csv
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/2009/2009.csv
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1985/1985.csv
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1997/1997.csv
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1999/1999.csv
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/1998/1998.csv
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/2002/2002.csv
/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/2004/2004.csv

Concatenate all the files in a single csv file

In [20]:
data_frame_list = []

for directory in glob.glob("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/multi-directory/*"):
    for files in glob.glob(directory + "/*"):
        data_frame_list.append(pd.read_csv(files))

data_frame_list

[     Unnamed: 0 Item_Identifier  Item_Weight Item_Fat_Content  \
 0             4           NCD19        8.930          Low Fat
 1             6           FDO10       13.650          Regular
 2            14           FDF32       16.350          Low Fat
 3            20           FDN22       18.850          Regular
 4            27           DRJ59       11.650          low fat
 ..          ...             ...          ...              ...
 927        8462           FDQ31        5.785          Regular
 928        8466           FDJ32       10.695          Low Fat
 929        8484           DRJ49        6.865          Low Fat
 930        8512           FDR26       20.700          Low Fat
 931        8518           FDF22        6.865          Low Fat

      Item_Visibility              Item_Type  Item_MRP Outlet_Identifier  \
 0           0.000000              Household   53.8614            OUT013
 1           0.012741            Snack Foods   57.6588            OUT013
 2           0.068024  Fruits and Vegetables  196.4426            OUT013
 3           0.138190            Snack Foods  250.8724            OUT013
 4           0.019356            Hard Drinks   39.1164            OUT013
 ..               ...                    ...       ...               ...
 927         0.053802  Fruits and Vegetables   85.9856            OUT013
 928         0.057744  Fruits and Vegetables   61.2536            OUT013
 929         0.000000            Soft Drinks  129.9652            OUT013
 930         0.042801                  Dairy  178.3028            OUT013
 931         0.056783            Snack Foods  214.5218            OUT013

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
 0                         1987        High               Tier 3
 1                         1987        High               Tier 3
 2                         1987        High               Tier 3
 3                         1987        High               Tier 3
 4                         1987        High               Tier 3
 ..                         ...         ...                  ...
 927                       1987        High               Tier 3
 928                       1987        High               Tier 3
 929                       1987        High               Tier 3
 930                       1987        High               Tier 3
 931                       1987        High               Tier 3

            Outlet_Type  Item_Outlet_Sales
 0    Supermarket Type1           994.7052
 1    Supermarket Type1           343.5528
 2    Supermarket Type1          1977.4260
 3    Supermarket Type1          3775.0860
 4    Supermarket Type1           308.9312
 ..                 ...                ...
 927  Supermarket Type1          1494.0552
 928  Supermarket Type1           673.7896
 929  Supermarket Type1          2324.9736
 930  Supermarket Type1          2479.4392
 931  Supermarket Type1          2778.3834

 [932 rows x 13 columns],
      Unnamed: 0 Item_Identifier  Item_Weight Item_Fat_Content  \
 0             9           FDU28       19.200          Regular
 1            25           NCD06       13.000          Low Fat
 2            53           FDA43       10.895          Low Fat
 3            54           NCP18       12.150          Low Fat
 4            73           FDG02        7.855          Low Fat
 ..          ...             ...          ...              ...
 921        8493           FDP21        7.420          Regular
 922        8494           NCI54       15.200          Low Fat
 923        8496           FDJ57        7.420          Regular
 924        8500           NCQ42       20.350          Low Fat
 925        8501           FDW21        5.340          Regular

      Item_Visibility              Item_Type  Item_MRP Outlet_Identifier  \
 0           0.094450           Frozen Foods  187.8214            OUT017
 1           0.099887              Household   45.9060            OUT017
 2           0.065042  Fruits and Vegetables  196.3794            OUT017
 3           0.028760              Household  151.4708            OUT017
 4           0.011325                 Canned  189.6188            OUT017
 ..               ...                    ...       ...               ...
 921         0.025886            Snack Foods  189.1872            OUT017
 922         0.000000              Household  110.4912            OUT017
 923         0.021696                Seafood  185.3582            OUT017
 924         0.000000              Household  125.1678            OUT017
 925         0.005998            Snack Foods  100.4358            OUT017

      Outlet_Establishment_Year  Outlet_Size Outlet_Location_Type  \
 0                         2007          NaN               Tier 2
 1                         2007          NaN               Tier 2
 2                         2007          NaN               Tier 2
 3                         2007          NaN               Tier 2
 4                         2007          NaN               Tier 2
 ..                         ...          ...                  ...
 921                       2007          NaN               Tier 2
 922                       2007          NaN               Tier 2
 923                       2007          NaN               Tier 2
 924                       2007          NaN               Tier 2
 925                       2007          NaN               Tier 2

            Outlet_Type  Item_Outlet_Sales
 0    Supermarket Type1          4710.5350
 1    Supermarket Type1           838.9080
 2    Supermarket Type1          3121.2704
 3    Supermarket Type1          4815.0656
 4    Supermarket Type1          2285.0256
 ..                 ...                ...
 921  Supermarket Type1          4727.1800
 922  Supermarket Type1          1637.8680
 923  Supermarket Type1          3715.1640
 924  Supermarket Type1          1907.5170
 925  Supermarket Type1          1508.0370

 [926 rows x 13 columns],
      Unnamed: 0 Item_Identifier  Item_Weight Item_Fat_Content  \
 0             1           DRC01        5.920          Regular
 1             5           FDP36       10.395          Regular
 2            16           NCB42       11.800          Low Fat
 3            31           NCS17       18.600          Low Fat
 4            32           FDP33       18.700          Low Fat
 ..          ...             ...          ...              ...
 923        8506           DRF37       17.250          Low Fat
 924        8511           FDF05       17.500          Low Fat
 925        8515           FDH24       20.700          Low Fat
 926        8516           NCJ19       18.600          Low Fat
 927        8521           FDN46        7.210          Regular

      Item_Visibility           Item_Type  Item_MRP Outlet_Identifier  \
 0           0.019278         Soft Drinks   48.2692            OUT018
 1           0.000000        Baking Goods   51.4008            OUT018
 2           0.008596  Health and Hygiene  115.3492            OUT018
 3           0.080829  Health and Hygiene   96.4436            OUT018
 4           0.000000         Snack Foods  256.6672            OUT018
 ..               ...                 ...       ...               ...
 923         0.084676         Soft Drinks  263.1910            OUT018
 924         0.026980        Frozen Foods  262.5910            OUT018
 925         0.021518        Baking Goods  157.5288            OUT018
 926         0.118661              Others   58.7588            OUT018
 927         0.145221         Snack Foods  103.1332            OUT018

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
 0                         2009      Medium               Tier 3
 1                         2009      Medium               Tier 3
 2                         2009      Medium               Tier 3
 3                         2009      Medium               Tier 3
 4                         2009      Medium               Tier 3
 ..                         ...         ...                  ...
 923                       2009      Medium               Tier 3
 924                       2009      Medium               Tier 3
 925                       2009      Medium               Tier 3
 926                       2009      Medium               Tier 3
 927                       2009      Medium               Tier 3

            Outlet_Type  Item_Outlet_Sales
 0    Supermarket Type2           443.4228
 1    Supermarket Type2           556.6088
 2    Supermarket Type2          1621.8888
 3    Supermarket Type2          2741.7644
 4    Supermarket Type2          3068.0064
 ..                 ...                ...
 923  Supermarket Type2          3944.8650
 924  Supermarket Type2          4207.8560
 925  Supermarket Type2          1571.2880
 926  Supermarket Type2           858.8820
 927  Supermarket Type2          1845.5976

 [928 rows x 13 columns],
       Unnamed: 0 Item_Identifier  Item_Weight Item_Fat_Content  \
 0              7           FDP10          NaN          Low Fat
 1             18           DRI11          NaN          Low Fat
 2             21           FDW12          NaN          Regular
 3             23           FDC37          NaN          Low Fat
 4             29           FDC14          NaN          Regular
 ...          ...             ...          ...              ...
 1458        8485           DRK37          NaN          Low Fat
 1459        8487           DRG13          NaN          Low Fat
 1460        8488           NCN14          NaN          Low Fat
 1461        8490           FDU44          NaN          Regular
 1462        8504           NCN18          NaN          Low Fat

       Item_Visibility              Item_Type  Item_MRP Outlet_Identifier  \
 0            0.127470            Snack Foods  107.7622            OUT027
 1            0.034238            Hard Drinks  113.2834            OUT027
 2            0.035400           Baking Goods  144.5444            OUT027
 3            0.057557           Baking Goods  107.6938            OUT019
 4            0.072222                 Canned   43.6454            OUT019
 ...               ...                    ...       ...               ...
 1458         0.043792            Soft Drinks  189.0530            OUT027
 1459         0.037006            Soft Drinks  164.7526            OUT027
 1460         0.091473                 Others  184.6608            OUT027
 1461         0.102296  Fruits and Vegetables  162.3552            OUT019
 1462         0.124111              Household  111.7544            OUT027

       Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
 0                          1985      Medium               Tier 3
 1                          1985      Medium               Tier 3
 2                          1985      Medium               Tier 3
 3                          1985       Small               Tier 1
 4                          1985       Small               Tier 1
 ...                         ...         ...                  ...
 1458                       1985      Medium               Tier 3
 1459                       1985      Medium               Tier 3
 1460                       1985      Medium               Tier 3
 1461                       1985       Small               Tier 1
 1462                       1985      Medium               Tier 3

             Outlet_Type  Item_Outlet_Sales
 0     Supermarket Type3          4022.7636
 1     Supermarket Type3          2303.6680
 2     Supermarket Type3          4064.0432
 3         Grocery Store           214.3876
 4         Grocery Store           125.8362
 ...                 ...                ...
 1458  Supermarket Type3          6261.8490
 1459  Supermarket Type3          4111.3150
 1460  Supermarket Type3          2756.4120
 1461      Grocery Store           487.3656
 1462  Supermarket Type3          4138.6128

 [1463 rows x 13 columns],
      Unnamed: 0 Item_Identifier  Item_Weight Item_Fat_Content  \
 0            11           FDA03       18.500          Regular
 1            13           FDS46       17.600          Regular
 2            15           FDP49        9.000          Regular
 3            24           FDR28       13.850          Regular
 4            34           DRH01       17.500          Low Fat
 ..          ...             ...          ...              ...
 925        8450           FDC28        7.905          Low Fat
 926        8461           FDB17       13.150          Low Fat
 927        8492           FDT34        9.300          Low Fat
 928        8517           FDF53       20.750              reg
 929        8522           DRG01       14.800          Low Fat

      Item_Visibility     Item_Type  Item_MRP Outlet_Identifier  \
 0           0.045464         Dairy  144.1102            OUT046
 1           0.047257   Snack Foods  119.6782            OUT046
 2           0.069089     Breakfast   56.3614            OUT046
 3           0.025896  Frozen Foods  165.0210            OUT046
 4           0.097904   Soft Drinks  174.8738            OUT046
 ..               ...           ...       ...               ...
 925         0.054987  Frozen Foods  108.6254            OUT046
 926         0.036672  Frozen Foods  182.5976            OUT046
 927         0.174350   Snack Foods  104.4964            OUT046
 928         0.083607  Frozen Foods  178.8318            OUT046
 929         0.044878   Soft Drinks   75.4670            OUT046

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
 0                         1997       Small               Tier 1
 1                         1997       Small               Tier 1
 2                         1997       Small               Tier 1
 3                         1997       Small               Tier 1
 4                         1997       Small               Tier 1
 ..                         ...         ...                  ...
 925                       1997       Small               Tier 1
 926                       1997       Small               Tier 1
 927                       1997       Small               Tier 1
 928                       1997       Small               Tier 1
 929                       1997       Small               Tier 1

            Outlet_Type  Item_Outlet_Sales
 0    Supermarket Type1          2187.1530
 1    Supermarket Type1          2145.2076
 2    Supermarket Type1          1547.3192
 3    Supermarket Type1          4078.0250
 4    Supermarket Type1          2085.2856
 ..                 ...                ...
 925  Supermarket Type1          1844.9318
 926  Supermarket Type1          4165.2448
 927  Supermarket Type1          2419.5172
 928  Supermarket Type1          3608.6360
 929  Supermarket Type1           765.6700

 [930 rows x 13 columns],
      Unnamed: 0 Item_Identifier  Item_Weight Item_Fat_Content  \
 0             0           FDA15        9.300          Low Fat
 1             2           FDN15       17.500          Low Fat
 2            10           FDY07       11.800          Low Fat
 3            12           FDX32       15.100          Regular
 4            17           FDP49        9.000          Regular
 ..          ...             ...          ...              ...
 925        8451           FDK21        7.905          Low Fat
 926        8467           FDV31        9.800               LF
 927        8470           FDW27        5.860          Regular
 928        8475           NCS17       18.600          Low Fat
 929        8479           FDL10        8.395          Low Fat

      Item_Visibility              Item_Type  Item_MRP Outlet_Identifier  \
 0           0.016047                  Dairy  249.8092            OUT049
 1           0.016760                   Meat  141.6180            OUT049
 2           0.000000  Fruits and Vegetables   45.5402            OUT049
 3           0.100014  Fruits and Vegetables  145.4786            OUT049
 4           0.069196              Breakfast   54.3614            OUT049
 ..               ...                    ...       ...               ...
 925         0.010028            Snack Foods  249.6408            OUT049
 926         0.000000  Fruits and Vegetables  175.2370            OUT049
 927         0.151088                   Meat  155.1314            OUT049
 928         0.080627     Health and Hygiene   92.5436            OUT049
 929         0.039554            Snack Foods   99.1042            OUT049

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
 0                         1999      Medium               Tier 1
 1                         1999      Medium               Tier 1
 2                         1999      Medium               Tier 1
 3                         1999      Medium               Tier 1
 4                         1999      Medium               Tier 1
 ..                         ...         ...                  ...
 925                       1999      Medium               Tier 1
 926                       1999      Medium               Tier 1
 927                       1999      Medium               Tier 1
 928                       1999      Medium               Tier 1
 929                       1999      Medium               Tier 1

            Outlet_Type  Item_Outlet_Sales
 0    Supermarket Type1          3735.1380
 1    Supermarket Type1          2097.2700
 2    Supermarket Type1          1516.0266
 3    Supermarket Type1          1589.2646
 4    Supermarket Type1           718.3982
 ..                 ...                ...
 925  Supermarket Type1          3254.4304
 926  Supermarket Type1          3881.6140
 927  Supermarket Type1          1551.3140
 928  Supermarket Type1           378.1744
 929  Supermarket Type1          2579.3092

 [930 rows x 13 columns],
      Unnamed: 0 Item_Identifier  Item_Weight Item_Fat_Content  \
 0             3           FDX07       19.200          Regular
 1            28           FDE51        5.925          Regular
 2            30           FDV38       19.250          Low Fat
 3            45           FDM39        6.420               LF
 4            65           FDC46       17.700               LF
 ..          ...             ...          ...              ...
 550        8400           NCE07        8.180          Low Fat
 551        8432           FDI16       14.000          Regular
 552        8473           DRI47       14.700          Low Fat
 553        8486           FDR20       20.000          Regular
 554        8509           FDG45        8.100          Low Fat

      Item_Visibility              Item_Type  Item_MRP Outlet_Identifier  \
 0           0.000000  Fruits and Vegetables  182.0950            OUT010
 1           0.161467                  Dairy   45.5086            OUT010
 2           0.170349                  Dairy   55.7956            OUT010
 3           0.089499                  Dairy  178.1002            OUT010
 4           0.195068            Snack Foods  185.4266            OUT010
 ..               ...                    ...       ...               ...
 550         0.021977              Household  140.6154            OUT010
 551         0.227261           Frozen Foods   54.3640            OUT010
 552         0.035016            Hard Drinks  144.3128            OUT010
 553         0.000000  Fruits and Vegetables   46.4744            OUT010
 554         0.214306  Fruits and Vegetables  213.9902            OUT010

      Outlet_Establishment_Year  Outlet_Size Outlet_Location_Type  \
 0                         1998          NaN               Tier 3
 1                         1998          NaN               Tier 3
 2                         1998          NaN               Tier 3
 3                         1998          NaN               Tier 3
 4                         1998          NaN               Tier 3
 ..                         ...          ...                  ...
 550                       1998          NaN               Tier 3
 551                       1998          NaN               Tier 3

In [22]:
final_data = pd.concat(data_frame_list)

In [23]:
final_data.head()

,Unnamed: 0,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
1,6,FDO10,13.65,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
2,14,FDF32,16.35,Low Fat,0.068024,Fruits and Vegetables,196.4426,OUT013,1987,High,Tier 3,Supermarket Type1,1977.4260
3,20,FDN22,18.85,Regular,0.138190,Snack Foods,250.8724,OUT013,1987,High,Tier 3,Supermarket Type1,3775.0860
4,27,DRJ59,11.65,low fat,0.019356,Hard Drinks,39.1164,OUT013,1987,High,Tier 3,Supermarket Type1,308.9312

In [25]:
final_data.shape

(8523, 13)

In [27]:
final_data.to_csv("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/merged_big_mart_sales.csv", index = False)

Challenge 3: Read a csv of a specific delimiter; eg: big_mart_sales_delimiter.csv is tab separated file

In [29]:
data_delimiter = pd.read_csv("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/big_mart_sales_delimiter.csv")
data_delimiter.head()

  Item_Identifier\tItem_Weight\tItem_Fat_Content\tItem_Visibility\tItem_Type\tItem_MRP\tOutlet_Identifier\tOutlet_Establishment_Year\tOutlet_Size\tOutlet_Location_Type\tOutlet_Type\tItem_Outlet_Sales
0  FDA15\t9.3\tLow Fat\t0.016047301\tDairy\t249.8...
1  DRC01\t5.92\tRegular\t0.019278216\tSoft Drinks...
2  FDN15\t17.5\tLow Fat\t0.016760075\tMeat\t141.6...
3  FDX07\t19.2\tRegular\t0.0\tFruits and Vegetabl...
4  NCD19\t8.93\tLow Fat\t0.0\tHousehold\t53.8614\...

In [31]:
data_delimiter = pd.read_csv("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/big_mart_sales_delimiter.csv", delimiter = "\t")
data_delimiter.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

Challenge 4: Read first 'N' Rows (When data is large)

In [33]:
read_sample_from_data = pd.read_csv("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/big_mart_sales.csv", nrows = 100)
read_sample_from_data.shape

(100, 12)

In [34]:
read_sample_from_data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

Challenge 5: Read specific columns only

In [36]:
read_specific_columns = pd.read_csv("/Users/annie/Documents/GitHub/Python-libraries-playground/datasets/big_mart_sales.csv", usecols = ["Item_Identifier", "Item_Type", "Item_MRP", "Item_Outlet_Sales"])
read_specific_columns.head()

  Item_Identifier              Item_Type  Item_MRP  Item_Outlet_Sales
0           FDA15                  Dairy  249.8092          3735.1380
1           DRC01            Soft Drinks   48.2692           443.4228
2           FDN15                   Meat  141.6180          2097.2700
3           FDX07  Fruits and Vegetables  182.0950           732.3800
4           NCD19              Household   53.8614           994.7052